# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [14]:
# Initial list of 5 integers
numbers = [1, 2, 3, 4, 5]
print("Original list:", numbers)

Original list: [1, 2, 3, 4, 5]


In [15]:
# Append: Add one element at the end
numbers.append(6)
print("After append(6):", numbers)

After append(6): [1, 2, 3, 4, 5, 6]


In [16]:
# Extend: Add multiple elements at the end
numbers.extend([7, 8])
print("After extend([7, 8]):", numbers)

After extend([7, 8]): [1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
# Insert: Add element at specific index
numbers.insert(2, 9)  # Insert 25 at index 2
print("After insert(2, 9):", numbers)

After insert(2, 9): [1, 2, 9, 3, 4, 5, 6, 7, 8]


In [18]:
# Remove: Remove first occurrence of a value
numbers.remove(4)
print("After remove(4):", numbers)

After remove(4): [1, 2, 9, 3, 5, 6, 7, 8]


In [19]:
# Pop: Remove and return element at index (default is last)
popped_value = numbers.pop()
print("After pop():", numbers)
print("Popped value:", popped_value)

After pop(): [1, 2, 9, 3, 5, 6, 7]
Popped value: 8


In [20]:
# Index: Find index of a value
index_of_3 = numbers.index(3)
print("Index of 3:", index_of_3)

Index of 3: 3


In [21]:
# Count: Count occurrences of a value
count_of_2 = numbers.count(2)
print("Count of 2:", count_of_2)

Count of 2: 1


In [22]:
# Sort: Sort the list in ascending order
numbers.sort()
print("After sort():", numbers)

After sort(): [1, 2, 3, 5, 6, 7, 9]


In [23]:
# Reverse: Reverse the list
numbers.reverse()
print("After reverse():", numbers)

After reverse(): [9, 7, 6, 5, 3, 2, 1]


In [24]:
# Clear: Remove all elements from the list
numbers.clear()
print("After clear():", numbers)

After clear(): []


## 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [25]:
# Creating a tuple with 3 student names
students = ("Farhan", "Akhzar", "Tanweer")
print("Original tuple:", students)

Original tuple: ('Farhan', 'Akhzar', 'Tanweer')


In [26]:
# Attempting to change the second name
students[1] = "Aman"  # This will raise an error

TypeError: 'tuple' object does not support item assignment

## Define:
   #### Tuples in Python are immutable, which means once created, their elements cannot be changed.

   #### When we try to assign a new value to students[1], Python throws a TypeError.

   #### This behavior ensures that tuples remain constant and safe from accidental modification.

# 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [28]:
# Creating a set with duplicate values
numbers = {1, 2, 3, 2, 4, 3, 5}

# Printing the set
print("Set of integers:", numbers)

Set of integers: {1, 2, 3, 4, 5}


# 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [29]:
# Step 1: Create the initial dictionary
student = {
    'name': 'Aman',
    'age': 19,
    'city': 'Mau'
}

# Step 2: Update the age
student['age'] = 20

# Step 3: Add a new key 'email'
student['email'] = 'aman@gmail.com'

# Step 4: Print the final dictionary
print("Final Dictionary:", student)


Final Dictionary: {'name': 'Aman', 'age': 20, 'city': 'Mau', 'email': 'aman@gmail.com'}


## 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [33]:
# Voting Eligibility Checker

# Take age as input
age = int(input("Enter your age: "))

# Check eligibility
if age >= 18:
    print("✅ You are eligible to vote.")
else:
    print("❌ You are not eligible to vote yet.")


Enter your age:  1


❌ You are not eligible to vote yet.


# 6.	Given a 'marks' variable, print the grade:

### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'


In [34]:
# Grade Calculator

# Input: marks
marks = int(input("Enter your marks: "))

# Determine grade
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

# Output result
print(f"Your grade is: {grade}")


Enter your marks:  67


Your grade is: C


# 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [36]:
# Number Check Script

# Input: number
num = int(input("Enter a number: "))

# Check conditions operater
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


Enter a number:  17


The number is positive.
It is odd.


# Section B: Numpy

## 8.	Create:

#### - A scalar using np.array(5)
#### - A 1D array with values 1 to 5
#### - A 2D array (2x3) with values from 10 to 60 in steps of 10


#####  Import libraries


In [37]:
import numpy as np

###  - A scalar using np.array(5)

In [38]:
scalar = np.array(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)


Scalar: 5
Shape: ()


### - A 1D array with values 1 to 5

In [39]:
one_d_array = np.array([1, 2, 3, 4, 5])
print("1D Array:", one_d_array)
print("Shape:", one_d_array.shape)


1D Array: [1 2 3 4 5]
Shape: (5,)


### - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [41]:
two_d_array = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", two_d_array)
print("Shape:", two_d_array.shape)


2D Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)


## 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [42]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

# Print the array
print("4x4 Random Integer Array (0–100):")
print(random_array)


4x4 Random Integer Array (0–100):
[[78 54  3 92]
 [70  4 16 92]
 [ 6 46 42 30]
 [84 67 74  8]]


## 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [43]:
import numpy as np
import pandas as pd

# Step 1: Create a 2D NumPy array of shape (3x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Step 2: Convert the NumPy array to a Pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

# Step 3: Print the DataFrame
print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


##### 🧠 Explanation:
#####  np.array() creates a 3×3 matrix.

##### pd.DataFrame() converts it into a DataFrame.

##### columns=['A', 'B', 'C'] assigns custom column names.

# Section C: Exploring Pandas

# 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:



In [44]:
import pandas as pd
import numpy as np

# Step 1: Create the DataFrame manually
data = {
    'Name': ['Aman', 'Bhavna', 'Akhzar', 'Tanweer', 'Esha', 'Farhan', 'Mohit', 'Manzoor', 'salam', 'Amit'],
    'Age': [25, 30, 22, 28, 35, 40, 29, 31, 27, 25],
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi'],
    'Salary': [50000, 60000, 55000, np.nan, 62000, 58000, 57000, 60000, np.nan, 50000]
}

df = pd.DataFrame(data)

# Step 2: Display info and statistics
print("🔍 DataFrame Info:")
print(df.info())

print("\n📊 Descriptive Statistics:")
print(df.describe())

# Step 3: Select 'Name' and 'City' columns
print("\n🧾 Selected Columns ('Name' and 'City'):")
print(df[['Name', 'City']])

# Step 4: Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\n🗑️ DataFrame after dropping 'City':")
print(df_dropped)

# Step 5: Fill missing 'Salary' values with mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\n💰 DataFrame after filling missing 'Salary' values with mean:")
print(df)

# Step 6: Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\n🚫 DataFrame after removing duplicate rows:")
print(df_no_duplicates)


🔍 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

📊 Descriptive Statistics:
             Age        Salary
count  10.000000      8.000000
mean   29.200000  56500.000000
std     5.245104   4535.573676
min    22.000000  50000.000000
25%    25.500000  53750.000000
50%    28.500000  57500.000000
75%    30.750000  60000.000000
max    40.000000  62000.000000

🧾 Selected Columns ('Name' and 'City'):
      Name     City
0     Aman    Delhi
1   Bhavna   Mumbai
2   Akhzar  Chennai
3  Tanweer    Delhi
4     Esha   Mumbai
5   Farhan  Chennai
6    Mohit    Delhi
7  Manzoor   Mumbai
8    salam  Chennai
9     Amit    Delhi

🗑️ DataFrame after 